Repository kubevirt/kubevirt-ssp-operator, pull requests merged in 2020-09, with the labels that each got.

#226 Added placement API to TemplateValidator
  functests/05-test(enable-when-ocp-ci-ready)-deploy-template-validator.sh
  functests/10-template-validator-unversioned-cr.yaml
  functests/10-test-template-validator-placement.sh
  pkg/apis/kubevirt/v1/types.go
  roles/KubevirtTemplateValidator/templates/service.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#231 Fixed an issue with TV placement API
  roles/KubevirtTemplateValidator/templates/service.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#232 Fixing default values for placement fields of tempalte validator
  functests/05-test-deploy-template-validator.sh
  functests/10-test-template-validator-placement.sh
  functests/10-test-template-validator-placement/10-template-validator-affinity-nodeSelector-tolerations.yaml
  functests/10-test-template-validator-placement/10-template-validator-empty-affinity-nodeSelector-tolerations.yaml
  roles/KubevirtTemplateValidator/templates/service.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#229 Add Placement API for NodeLabeller
  deploy/crds/ssp.kubevirt.io_kubevirtnodelabellerbundles_crd.yaml
  deploy/crds/ssp.kubevirt.io_kubevirttemplatevalidators_crd.yaml
  functests/11-test-node-labeller-placement.sh
  functests/11-test-node-labeller-placement/11-node-labeller-affinity-nodeSelector-tolerations.yaml
  functests/11-test-node-labeller-placement/11-node-labeller-empty-affinity-nodeSelector-tolerations.yaml
  pkg/apis/kubevirt/v1/types.go
  roles/KubevirtNodeLabeller/templates/kubevirt-node-labeller-ds.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#212 Create Namespace and RBAC for Golden Images
  _defaults.yml
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
  deploy/role.yaml
  functests/12-test-os-imaes-namespace_rbac.sh
  roles/KubevirtCommonTemplatesBundle/tasks/main.yml
  roles/KubevirtCommonTemplatesBundle/templates/kubevirt-os-images-editrole.yaml.j2
  roles/KubevirtCommonTemplatesBundle/templates/kubevirt-os-images-namespace.yaml.j2
  roles/KubevirtCommonTemplatesBundle/templates/kubevirt-os-images-viewrole.yaml.j2
  roles/KubevirtCommonTemplatesBundle/templates/kubevirt-os-images-viewrolebinding.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#234 add missing version field in olm-catalog
  build/update-csv.py
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#235 updated common templates to version v0.12.0
  _defaults.yml
  roles/KubevirtCommonTemplatesBundle/files/common-templates-v0.12.0.yaml
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/XXL

#236 bump validator version
  _defaults.yml
Labels: approved, dco-signoff: yes, release-note, size/XS

#233 Added a missing testid to a test (Explainable CRDs)
  functests/09-test-ensure-crds-are-explainable.sh
Labels: dco-signoff: yes, lgtm, release-note-none, size/XS

#237 fix missing version in csv
  build/update-csv.py
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#238 [backport] fix missing version in csv
  build/update-csv.py
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#241 updated common templates to version v0.12.1
  _defaults.yml
  roles/KubevirtCommonTemplatesBundle/files/common-templates-v0.12.1.yaml
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/XXL

#240 Added more Tests and Polarian testids
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
  functests/10-test-template-validator-placement.sh
  functests/11-test-node-labeller-placement.sh
  functests/12-test-os-imaes-namespace_rbac.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
