Repository kubevirt/kubevirt-ssp-operator, pull requests merged in 2020-10, with the labels that each got.

#239 Fix placement api
  functests/10-test-template-validator-placement.sh
  functests/11-test-node-labeller-placement.sh
  roles/KubevirtCommonTemplatesBundle/tasks/main.yml
  roles/KubevirtNodeLabeller/tasks/main.yml
  roles/KubevirtTemplateValidator/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#244 updated common templates to version v0.12.2
  _defaults.yml
  roles/KubevirtCommonTemplatesBundle/files/common-templates-v0.12.2.yaml
Labels: dco-signoff: no, lgtm, release-note, size/XXL

#246 [Backport] updated common templates to version v0.12.2
  _defaults.yml
  roles/KubevirtCommonTemplatesBundle/files/common-templates-v0.12.2.yaml
Labels: dco-signoff: no, release-note-none, size/XXL

#243 Add permissions to allow cloning of Images
  deploy/olm-catalog/kubevirt-ssp-operator.clusterserviceversion.yaml
  functests/12-test-os-imaes-namespace_rbac.sh
  roles/KubevirtCommonTemplatesBundle/templates/kubevirt-os-images-viewrolebinding.yaml.j2
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#249 fix generation of crds
  hack/generate-crds.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#252 Add documentation for Placement API
  docs/dev/placement-api.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
