Repository kubevirt/kubevirt-ssp-operator, pull requests merged in 2020-08, with the labels that each got.

#202 Changed way how templates are deployed.
  build/Dockerfile
  filter_plugins/k8s_inject_ownership.py
  roles/ClaimOwnership/tasks/main.yml
  roles/KubevirtCommonTemplatesBundle/tasks/main.yml
  roles/KubevirtNodeLabeller/tasks/main.yml
Labels: dco-signoff: yes, lgtm, size/M

#205 Added OWNERS file
  OWNERS
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#206 updated common templates to version v0.11.3
  _defaults.yml
  roles/KubevirtCommonTemplatesBundle/files/common-templates-v0.11.3.yaml
Labels: approved, dco-signoff: no, do-not-merge/release-note-label-needed, lgtm, size/XXL

#209 Added PR and issue templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#210 Modified deployment scripts to support OCP CI deployment
  Makefile
  hack/deploy-operator.sh
  hack/make-manifests.sh
Labels: dco-signoff: yes, release-note-none

#211 Fixing make target for OCP CI
  Makefile
Labels: dco-signoff: yes, release-note-none

#213 Ocp ci integration
  Makefile
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#214 Made sure the test namespace exists before deployment
  hack/deploy-operator.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#215 Created a ci-deploy make target
  Makefile
  hack/deploy-operator.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed

#218 Modified deployment scripts and tests to support OCP CI deployment
  deploy/crds/kubevirt_v1_commontemplatesbundle_cr.yaml
  deploy/crds/kubevirt_v1_metricsaggregation_cr.yaml
  deploy/crds/kubevirt_v1_nodelabellerbundle_cr.yaml
  deploy/crds/kubevirt_v1_templatevalidator_cr.yaml
  functests/02-test-deploy-templates-openshift.sh
  functests/03-test-deploy-templates-different-namespace.sh
  functests/04-test-deploy-templates-operator-namespace.sh
  functests/05-test-deploy-template-validator.sh
  functests/07-test-conditions-templates.sh
  functests/08-test-conditions-templates.sh
  functests/08-test-deploy-prometheus-rules.sh
  functests/common-templates-unversioned-cr.yaml
  functests/node-labeller-unversioned-cr.yaml
  functests/ssp-op-functest-NAA5uDdT
  hack/deploy-operator.sh
  roles/KubevirtMetricsAggregation/tasks/main.yml
  roles/KubevirtTemplateValidator/tasks/main.yml
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/L

#219 Merge branch 'ocp-ci-integration' into ocp-ci-integration
  functests/06-test-deploy-prometheus-rules.sh
  hack/deploy-operator.sh
Labels: dco-signoff: no, do-not-merge/release-note-label-needed, size/L

#217 Removed operand versions from CRs
  deploy/crds/kubevirt_v1_commontemplatesbundle_cr.yaml
  deploy/crds/kubevirt_v1_metricsaggregation_cr.yaml
  deploy/crds/kubevirt_v1_nodelabellerbundle_cr.yaml
  deploy/crds/kubevirt_v1_templatevalidator_cr.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#216 [Bugfix] Removed traces of ClaimOwnership role
  roles/KubevirtMetricsAggregation/tasks/main.yml
  roles/KubevirtTemplateValidator/tasks/main.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#221 Improved deployment process and prepare for OCP CI
  Makefile
  functests/02-test-deploy-templates-openshift.sh
  functests/03-test-deploy-templates-different-namespace.sh
  functests/04-test-deploy-templates-operator-namespace.sh
  functests/05-test(enable-when-ocp-ci-ready)-deploy-template-validator.sh
  functests/07-test-conditions-templates.sh
  functests/07-test-deploy-prometheus-rules.sh
  functests/08-test-conditions-templates.sh
  functests/08-test-deploy-prometheus-rules.sh
  functests/common-templates-unversioned-cr.yaml
  functests/node-labeller-unversioned-cr.yaml
  hack/deploy-operator.sh
  hack/make-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#223 [OCP CI] Deploying the operator image on OCP CI using tags instead of digest
  Makefile
  hack/make-ocp-ci-manifests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#224 Removed the manifests generation from functests make target
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
